version: '3'
services:
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
  backend:
    image: node:18-alpine
    container_name: node
    restart: always
    depends_on:
      - mongo
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: yarn dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"