version: '3'
services:
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
      MONGO_INITDB_DATABASE: database
  backend:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile  
    env_file:
      - .env
    ports:
      - 3000:3000
    command: "yarn dev"